Заготовка проекта
sashadudkina5/BurgerApp_React pull request #1
Opened 2023-09-24 19:17 UTC by sashadudkina5

2023-09-24 19:36 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Логичный и понятный код
- Хорошая декомпозиция компонентов
- Правильно использовали `propTypes`

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- У верхней и нижней булки должны быть надписи "Верх" и "Низ" соответственно.
- Булки не должны скролиться, только контент между ними
- во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать
- Использовать атрибут `style` следует только для динамических стилей, во всех остальных случаях следует использовать классовые стили

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-09-24 19:36 UTC, andryxxa93 commented on src/components/AppHeader/appHeader.js
> +        <a href='#' className={appHeaderStyles.link}>
**Можно лучше**
нарушено форматирование кода - проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Практически все современные редакторы умеют автоматически форматировать код. В vscode для этого **достаточно нажать F1 и в выпадающем списке выбрать пункт Format Document**.
 Постарайтесь использовать автоматическое форматирование, это сильно экономит время, а Ваш код будет всегда красив. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

2023-09-24 19:36 UTC, andryxxa93 commented on src/components/BurgerIngredients/burgerIngredients.js
> +    const bunIngredients = ingredients.filter((ingredient) => ingredient.type === 'bun');
**Можно лучше**
Сложные операции желательно оборачивать в хук `useMemo` чтобы избежать ненужных выполнений. 
https://ru.reactjs.org/docs/hooks-reference.html#usememo

2023-09-24 19:36 UTC, andryxxa93 commented on src/components/ProductAdded/productAdded.js
> +      PropTypes.shape({
**Надо исправить**

во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать

2023-09-27 15:35 UTC, sashadudkina5 commented
Добавила второй коммит

2023-09-28 06:24 UTC, andryxxa93 commented
Промежуточная работа принята, вы можете приступать к финальному этапу сдачи работы. Удачи!

2023-10-12 09:39 UTC, merged